import { httpRouter } from "convex/server";
import { httpAction } from "./_generated/server";
import { api } from "./_generated/api";
import { authComponent, createAuth } from "./auth";
import { SITE_URL, BETTER_AUTH_URL } from "./env";

/**
 * Better Auth HTTP routes, served by Convex at `${CONVEX_SITE_URL}/api/auth/*`.
 * The Vite SPA talks to these directly — there is no app-tier server or proxy
 * (see docs/contracts/auth-flow.md). CORS is restricted to the public site
 * origin (SITE_URL) so only our frontend can drive the OAuth/session endpoints.
 */
const http = httpRouter();

authComponent.registerRoutes(http, createAuth, {
  cors: {
    allowedOrigins: [SITE_URL ?? BETTER_AUTH_URL ?? ""],
  },
});

// ─────────────────────────────────────────────────────────────────────────────
// Open Graph / social-sharing meta endpoint (FEN-373).
//
// `GET /api/og/c/:slug` — returns a minimal HTML page with correct Open Graph
// and Twitter Card meta tags for the given canvas. The Caddy proxy rewrites
// social-bot User-Agents on `/c/:slug` to this path before the SPA fallback,
// so shared links render rich previews (title + thumbnail) on Discord, X,
// Slack, etc. Real users keep hitting the SPA as before.
//
// Image: resolves the pre-rendered canvas thumbnail from Convex storage when
// available (PNG, generated by the worker off the hot path — FEN-33/G-Perf3).
// Falls back to the static brand SVG for canvases without a thumbnail yet.
//
// The HTML includes a `<meta http-equiv="refresh">` so that any crawler that
// does execute it redirects back to the canonical SPA URL — the OG page itself
// is never meant for human navigation (x-robots-tag: noindex).
// ─────────────────────────────────────────────────────────────────────────────

const BRAND_TITLE = "LivePlace — Canvas collaboratif Twitch";
const BRAND_DESC =
  "Pose tes pixels sur la fresque collaborative en direct sur Twitch. Canvas de pixels temps réel.";

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function buildOgHtml(opts: {
  title: string;
  description: string;
  imageUrl: string;
  canonicalUrl: string;
}): string {
  const { title, description, imageUrl, canonicalUrl } = opts;
  const t = escapeHtml(title);
  const d = escapeHtml(description);
  const img = escapeHtml(imageUrl);
  const url = escapeHtml(canonicalUrl);
  return `<!doctype html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <title>${t}</title>
    <meta name="description" content="${d}" />
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="LivePlace" />
    <meta property="og:title" content="${t}" />
    <meta property="og:description" content="${d}" />
    <meta property="og:image" content="${img}" />
    <meta property="og:url" content="${url}" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${t}" />
    <meta name="twitter:description" content="${d}" />
    <meta name="twitter:image" content="${img}" />
    <meta http-equiv="refresh" content="0;url=${url}" />
  </head>
  <body><a href="${url}">${t}</a></body>
</html>`;
}

const ogCanvasHandler = httpAction(async (ctx, req) => {
  const reqUrl = new URL(req.url);
  // pathPrefix="/api/og/c/" → everything after that prefix is the slug.
  const rawSlug = reqUrl.pathname.slice("/api/og/c/".length).replace(/^\/+|\/+$/g, "");
  const slug = decodeURIComponent(rawSlug);

  const siteUrl = (SITE_URL ?? "https://liveplace.tv").replace(/\/$/, "");
  const brandImage = `${siteUrl}/og-brand.png`;
  const canonicalUrl = slug ? `${siteUrl}/c/${encodeURIComponent(slug)}` : siteUrl;

  let title = BRAND_TITLE;
  let description = BRAND_DESC;
  let imageUrl = brandImage;

  if (slug) {
    const canvas = await ctx.runQuery(api.canvases.getCanvasBySlug, { slug });
    if (canvas) {
      title = `${canvas.title} — LivePlace`;
      description = `Rejoins la fresque "${canvas.title}" sur LivePlace — canvas collaboratif Twitch.`;
      if (canvas.thumbnailStorageId) {
        const thumbUrl = await ctx.storage.getUrl(canvas.thumbnailStorageId);
        if (thumbUrl) imageUrl = thumbUrl;
      }
    }
  }

  return new Response(
    buildOgHtml({ title, description, imageUrl, canonicalUrl }),
    {
      headers: {
        "content-type": "text/html; charset=utf-8",
        "cache-control": "public, max-age=60, stale-while-revalidate=300",
        "x-robots-tag": "noindex",
      },
    },
  );
});

http.route({
  pathPrefix: "/api/og/c/",
  method: "GET",
  handler: ogCanvasHandler,
});

export default http;
